export const workoutsTypes = {
  GET_WORKOUTS: 'GET_WORKOUTS',
  ADD_WORKOUT: 'ADD_WORKOUT',
  DELETE_WORKOUT: 'DELETE_WORKOUT',
  UPDATE_WORKOUT: 'UPDATE_WORKOUT',
  CHANGE_DAY: 'CHANGE_DAY',
  TOGGLE_NEW_WORKOUT: 'TOGGLE_NEW_WORKOUT'
};

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const REGISTER_FORM = 'REGISTER_FORM';
export const LOGIN_FORM = 'LOGIN_FORM';
