export const workoutsTypes = {
  GET_WORKOUTS: 'GET_WORKOUTS',
  ADD_WORKOUT: 'ADD_WORKOUT',
  DELETE_WORKOUT: 'DELETE_WORKOUT',
  UPDATE_WORKOUT: 'UPDATE_WORKOUT',
  CHANGE_DAY: 'CHANGE_DAY',
  TOGGLE_NEW_WORKOUT: 'TOGGLE_NEW_WORKOUT'
};

export const authTypes = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  USER_LOADED: 'USER_LOADED',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  REGISTER_FORM: 'REGISTER_FORM',
  LOGIN_FORM: 'LOGIN_FORM'
};
